//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAftermath_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Background
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Background()
        {
            this.Characters = new HashSet<Character>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Training { get; set; }
        public string Skills { get; set; }
        public Nullable<byte> Combat { get; set; }
        public Nullable<byte> Construction { get; set; }
        public Nullable<byte> Covert { get; set; }
        public Nullable<byte> Craftsman { get; set; }
        public Nullable<byte> Social { get; set; }
        public Nullable<byte> Survival { get; set; }
        public Nullable<byte> Technology { get; set; }
        public Nullable<byte> Transportation { get; set; }
        public bool Disabled { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<byte> Science { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Character> Characters { get; set; }
    }
}
