//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAftermath_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AdminPassword { get; set; }
        public string PlayerPassword { get; set; }
        public Nullable<System.Guid> Storyteller { get; set; }
        public bool Locked { get; set; }
        public bool Closed { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
