//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAftermath_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.AccountStatus = new HashSet<AccountStatu>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Season { get; set; }
        public string Year { get; set; }
        public string Description { get; set; }
        public string AdminPassword { get; set; }
        public string PlayerPassword { get; set; }
        public bool TellActive { get; set; }
        public bool Locked { get; set; }
        public bool Closed { get; set; }
        public string ConferenceLink { get; set; }
        public string MapLoc { get; set; }
        public string PictureLoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountStatu> AccountStatus { get; set; }
    }
}
