//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAftermath_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.AccountStatus = new HashSet<AccountStatus>();
            this.CharacterAbilities = new HashSet<CharacterAbility>();
            this.CharacterAttributes = new HashSet<CharacterAttribute>();
            this.CharacterExps = new HashSet<CharacterExp>();
            this.CharacterSkills = new HashSet<CharacterSkill>();
            this.IDMarks = new HashSet<IDMark>();
            this.CampaignNotes = new HashSet<CampaignNote>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid AccountID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string Birthdate { get; set; }
        public string Sex { get; set; }
        public string Height { get; set; }
        public string Ethnicity { get; set; }
        public string HairColor { get; set; }
        public string HairStyle { get; set; }
        public string FacialHair { get; set; }
        public string EyeColor { get; set; }
        public string Habitat { get; set; }
        public System.Guid History { get; set; }
        public string Strategy { get; set; }
        public System.Guid Background { get; set; }
        public string PictureLoc { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountStatus> AccountStatus { get; set; }
        public virtual Background Background1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterAbility> CharacterAbilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterAttribute> CharacterAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterExp> CharacterExps { get; set; }
        public virtual History History1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterSkill> CharacterSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDMark> IDMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignNote> CampaignNotes { get; set; }
    }
}
