//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAftermath_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDMark
    {
        public System.Guid ID { get; set; }
        public System.Guid CharacterID { get; set; }
        public string EyeColor { get; set; }
        public string HairColor { get; set; }
        public string HairStyle { get; set; }
        public string FacialHair { get; set; }
        public string Head { get; set; }
        public string Face { get; set; }
        public string Neck { get; set; }
        public string LeftShoulder { get; set; }
        public string RightShoulder { get; set; }
        public string LeftRibs { get; set; }
        public string RightRibs { get; set; }
        public string LeftBicep { get; set; }
        public string RightBicep { get; set; }
        public string LowerBack { get; set; }
        public string Stomach { get; set; }
        public string LeftForearm { get; set; }
        public string RightForearm { get; set; }
        public string Rear { get; set; }
        public string Groin { get; set; }
        public string LeftHand { get; set; }
        public string RightHand { get; set; }
        public string LeftThigh { get; set; }
        public string RightThigh { get; set; }
        public string LeftCalf { get; set; }
        public string RightCalf { get; set; }
        public string LeftFoot { get; set; }
        public string RightFoot { get; set; }
    
        public virtual Character Character { get; set; }
    }
}
