//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAftermath_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skill()
        {
            this.CharacterSkills = new HashSet<CharacterSkill>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string ShortTxt { get; set; }
        public string LongTxt { get; set; }
        public string Class { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Formula { get; set; }
        public string Requirements { get; set; }
        public bool Disabled { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterSkill> CharacterSkills { get; set; }
    }
}
